### ISSUE TITLE
Connection hangs

### ISSUE THREAD

**Issue by pothos** [maxmcd/webtty#18]
I only see these messages when typing as client:

`Failed to push SCTP packet: Failed handling chunk: Failure handling SACK: SACK Cumulative ACK 3408757062 is older than ACK point 3408757062`

**Comment by maxmcd** [comment]
I've been running into this from time to time as well. I think it's related to the size of the packets being sent. Are you seeing this immediately or after a period of use?

**Comment by pothos** [comment]
Not immediately but after some time. Otherwise it was fun to use but I still switched back to hidden tor services because ssh has a better handling of providing a remote terminal. I found webtty to break quickly when `nano` is used or otherwise the input is not linearly entered. Maybe this is due to losing a packet or not implementing the ANSI sequences of the terminal correctly? I don't know if these issues are related but maybe a new ticket is needed.

**Comment by Sean-Der** [comment]
Hi @pothos thanks for reporting!

This was a bug with `pion/sctp` that has been fixed, do you mind trying `v0.3.0`? Sorry this took so long I am gonna spend the weekend getting the project back up to speed :)

**Comment by pothos** [comment]
No problem, I can understand ;)
I can't reproduce the bug now but I'm also in a different network setting. Anyway good news.
