### ISSUE TITLE
Quitting with an unexpected error: "failed to parse IP address"

### ISSUE THREAD

**Issue by spac3-monk3y** [maxmcd/webtty#21]
When pasting the answer from web, the process fail with the following message:

`Quitting with an unexpected error: "failed to parse IP address"`

**Comment by Sean-Der** [comment]
Hey @spac3-monk3y 

Can you try updating `pion/webrtc`? Chromium added a new candidate type called `mDNS` and it is only supported in `v2.1.0+` 

thanks!

**Comment by Sean-Der** [comment]
https://bloggeek.me/psa-mdns-and-local-ice-candidates-are-coming/ a little about it

**Comment by Sean-Der** [comment]
Hey everyone!

I opened a PR for this https://github.com/maxmcd/webtty/pull/22 when I get the build green `WebTTY` will work with mDNS candidates (and this error will use it)

thanks for using it and reporting the issue :)

**Comment by Sean-Der** [comment]
This is fixed with https://github.com/maxmcd/webtty/commit/4881624c1fe53da315b949b54214338c0d2976f5

I also cut a new release `v0.3.0`
