### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by dayblox** [maxmcd/webtty#3]
When entering the response of the client, I get 'Quitting with an unexpected error: "unexpected end of JSON input"'.

**Comment by maxmcd** [comment]
I usually get that error when I paste in the response incorrectly. Can you paste your response here?

**Comment by dayblox** [comment]
HaTSJ54HnxKLye5K5uRcP16R8XzUCUCRCV723QCZRNBohJ94PvKPtj5imBDHyWaLVR4J9JCZRuqJVCiDFPfRHFvVhGo3ipgjshN1T69SsvEFepDVRUMbx4y7vhJLuEKL7NU1zWqNd8RJK4Ma6Ntz2e3cQpMLga49czGo3jLMcnKdhnc62BeA6nhU5gDPPnMDZhq4dzxNzLHy2vpBQTKwQFRDoCMCaEqAvFHAgDRAtV3HeuRWdpRFp5tjouYAuso9AHhPQ7bH819TQaQ5CpnvZ6Jjy1fEiywxokBcRRebk2nYxEJCrtLai8G64n4UYatx8J4UmsRFAvTvXAHDWKeq4Z7eiwRretKSZYo7juNzGHk32DZqB7ntcsMBQaFGafDkbhF3tikddoPW1rvZ5qmJPS4SL6P273c17zqyqTCY6V44JgdiM4f7ZydsAtpucamjE7sxcHnfdukazfgPTXZXcnQkzKkMh5Xj9dRpZRjG9KVyj49fi6LtWdRjSHvKbLJsLvh9agrHHmNVZ7AyPD7TWymyut6LzkBAyzMdtuQJ3B77MFg88t1oKmYsGo2tGXF8L6vNu9WsZKQ3Z17mj2vDdASVENxshogwpxPypnKy323Dbdk3XVkH2qzRNrhpLgAzNAYUKs6gUxLxBbrqx2e6WWvxWAiVXn5kyKKnF2pwNFE9NrJb7AZkLpyeoaRfZmw8UN162hDFN8t74oNmAAX3Dk6XetVDvC5wdzmSe8ti2d7iSdYs1KXfcevnEMevQtsaAXxhEbCaPubQrHSvAjtdqypVvAKjzcUTGMZ1FuXJmowAcb1jixKFmtCiDvP5tTR6CBLETVpaVmhEVFmP9JyFNBxccmHaAsvxzYo96a2fWKimh8JaoWGuvf88dWyNiY68

**Comment by dayblox** [comment]
The answer seems to always be about 40 characters shorter.

**Comment by maxmcd** [comment]
Hmm, its working for me. 897-40 is 857. I've run into issues with the terminal stdin buffer, which is 1024 bytes in my terminal, but I'm not sure why 857 wouldn't work. I've been working on ways to further compress the byte size of the message, maybe those fixes will solve this.

**Comment by advilm** [comment]
I have a script which fetches the token so I don't have to deal with it. It fetches the token correctly but for some reason I keep getting unexpected end of JSON input. When I copy paste the outputted token it works fine 
![](https://advil.cf/u/Dwpmk1.png)
But for example if I use `webtty $TOKEN` I just get `Quitting with an unexpected error: "unexpected end of JSON input"`
