### ISSUE TITLE
pions/webrtc needs go version > 1.8

### ISSUE THREAD

**Issue by pawamoy** [maxmcd/webtty#4]
Hi, just got this message when doing `go get -u github.com/maxmcd/webtty` with go 1.8:

```
# github.com/pions/webrtc
.go/src/github.com/pions/webrtc/media.go:11: syntax error: unexpected = in type declaration
```

Tried again with go version 1.9.7 and it worked. I know it depends on pions/webrtc but maybe you could add a note in the README about the minimum required go version :slightly_smiling_face:

**Comment by hemreari** [comment]
I tried and worked for go 1.9 but didn't work for go 1.7.

**Comment by backkem** [comment]
This happens because we've used type aliases to deprecate parts of the ``pions/webrtc`` public API. Type aliases where [introduced ](https://golang.org/doc/go1.9) with go 1.9.

**Comment by crazy4groovy** [comment]
I'm getting:
```
C:\Users\me>go get -u github.com/maxmcd/webtty
# github.com/maxmcd/webtty
.go\src\github.com\maxmcd\webtty\client.go:26:18: undefined: pty.GetsizeFull
.go\src\github.com\maxmcd\webtty\client.go:47:21: undefined: syscall.SIGWINCH
.go\src\github.com\maxmcd\webtty\client.go:57:9: undefined: syscall.SIGWINCH
.go\src\github.com\maxmcd\webtty\host.go:37:18: undefined: pty.Start
.go\src\github.com\maxmcd\webtty\host.go:128:17: undefined: pty.GetsizeFull
.go\src\github.com\maxmcd\webtty\host.go:142:16: undefined: pty.Setsize
```
After I just installed latest go v1.11.2

**Comment by pawamoy** [comment]
Installed correctly with go 1.9, 1.9.7, 1.10, 1.10.5, 1.11 and 1.11.2.
