### ISSUE TITLE
How to self-host the webtty web terminal

### ISSUE THREAD

**Issue by VladislavGatsenko** [maxmcd/webtty#52]
Can you suggest how to deploy your server part on your domain, instead of https://maxmcd.github.io/webtty/ ?

I would be very grateful to you.

**Comment by maxmcd** [comment]
Definitely. It is all static, hosted on Github Pages. You can view the source files here: https://github.com/maxmcd/webtty/tree/gh-pages

And host them wherever you want.

ie, with python:
```
git clone git@github.com:maxmcd/webtty.git
cd webtty && git checkout gh-pages
python -m http.server 8080
```

**Comment by VladislavGatsenko** [comment]
Thanks, it turned out to be much easier than I was trying to make it :)

Sad that the project hasn't been updated in a while, it's very cool!

**Comment by erbing** [comment]
Can I build my own client-web locally?
