### ISSUE TITLE
Onmessage has not been set for Datachannel data 0 ERROR

### ISSUE THREAD

**Issue by sgeisbacher** [maxmcd/webtty#7]
often (every 2nd or 3rd try) i get the error that the Onmessage-event-handler is not set after successfully established connection:
```
...
Terminal session started:
Onmessage has not been set for Datachannel data 0
                                                  Onmessage has not been set for Datachannel data 0
                                                                                                    Onmessage has not been set for Datachannel data 0
```
the connection is successful because for every keypress on the host-side i get one "Onmessage has not been set for Datachannel data 0" error-message on the client side.

dont know, but maybe cause some of the function you are using from webrtc are deprecated? e.g. Onmessage (https://github.com/pions/webrtc/blob/0043a4bf9adfdf01f8ece009432384a621b56f2c/rtcdatachannel.go#L96) or rtcPeerConnection *RTCPeerConnection (https://github.com/pions/webrtc/blob/0043a4bf9adfdf01f8ece009432384a621b56f2c/rtcdatachannel.go#L107) 🤷‍♂️

**Comment by maxmcd** [comment]
I was actually unable to get `OnMessage` to work, but will make the switch soon enough. What is the behavior of the other side of the connection when you get this error?

**Comment by Sean-Der** [comment]
Hi @sgeisbacher are you still getting this error?

Sorry I didn't get to this sooner, but I am spending the weekend getting the project cleaned up. Please re-open this issue if you are still get this with `v0.3.0`

thanks!
